## 📚 Tabela de Conteúdos

- [Parte 1: Vetores](#🧮-Parte-1:-Vetores)
- [Parte 2: Matrizes](#🧮-Parte-2:-Matrizes-e-Álgebra-Linear)
- [Parte 3: Estatística e aplicações](#📊-Parte-3:-Estatística-com-NumPy)  
- [Onde isso é usado?](#🧩-Aplicações-Reais-—-Onde-isso-é-usado?)

# 🧮 Parte 1: Vetores

🔹 Conceito
- Um vetor é uma estrutura unidimensional que armazena uma sequência ordenada de elementos. 
- Em termos matemáticos, ele pode ser visto como uma matriz de uma única linha ou uma única coluna.
- Já em programação (como no NumPy), é representado como um array 1D.

## 🧠 Aplicações comuns:
- Representação de pontos ou direções no espaço

- Armazenamento de séries temporais ou listas de dados

- Operações com álgebra vetorial (produto escalar, norma, etc.)

- Entrada e saída de modelos de machine learning

- Vetores de características em estatística e ciência de dados
---

## 🧪 Criação de dois vetores com 4 elementos e a realização da soma entre eles.


In [1]:
import numpy as np

In [2]:
# Criando vetores
v1 = np.array([2, 3])
v2 = np.array([1, 5])

In [3]:
# Soma
print("Soma:", v1 + v2)

Soma: [3 8]


---
## 🧪 Aplicando o produto escalar

- Produto escalar, é como a soma porém aplicamos a multiplicação, (2 * 1 = 2) + (3 * 5 = 15) 2 + 15 = 17


In [4]:
print("Matriz v1:\n\n", v1,"\n")
print("Matriz v2:\n\n", v2,"\n")

print("Produto escalar:", np.dot(v1, v2))

Matriz v1:

 [2 3] 

Matriz v2:

 [1 5] 

Produto escalar: 17


---
# 🧪 Operações com slicing
## Invertendo o vetor

# 🧪 Norma de Vetores

In [5]:
v = np.array([1, 2, 3, 4, 5])
print("Inverso:", v[::-1])


Inverso: [5 4 3 2 1]


---
# 🧪 Norma de Vetores
- Mede o “tamanho” ou magnitude de um vetor. Muito usado em geometria e machine learning.
- eleva o primeiro elemento ao quadrado ou seja 3²
- eleva o segundo elemento ao quadrado ou seja 4²
- 3² + 4² = 9 + 16 = 25
- agora aplicamos a raiz de 25 e dará o valor 5

In [6]:
v = np.array([3, 4])
norma = np.linalg.norm(v)
print("Norma do vetor:", norma)

Norma do vetor: 5.0


---
# 🧮 Parte 2: Matrizes e Álgebra Linear

- Uma matriz é uma estrutura matemática bidimensional composta por linhas e colunas, onde cada elemento ocupa uma posição definida.
- Em programação (especialmente com NumPy), ela é representada como um array 2D, sendo amplamente utilizada para organizar dados, realizar cálculos numéricos e representar sistemas lineares.

## 🧠 Aplicações comuns:
- Representação de imagens (pixels)

- Sistemas de equações lineares

- Transformações geométricas

- Operações em álgebra linear

- Modelagem em física, estatística e machine learning
---

## 🧪 Multiplicação das matrizes A (2×3) e B (3×2) que resultará em uma matriz 2×2.


In [7]:
# Matriz
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[1, 4],
              [2, 5],
              [3, 6]])

In [8]:
# Multiplicação de matrizes
print("Matriz resultante:\n", np.dot(A, B))

Matriz resultante:
 [[14 32]
 [32 77]]


---
## 🧪 Multiplicação de uma matriz de D (3×3) pelo vetor C, resultando em um novo vetor de 3 elementos.


In [9]:
# Matriz
C = np.array([1, 2, 3])

D = np.array([[1, 4, 7],
              [2, 5, 8],
              [3, 6, 9]])

In [10]:
print("Vetor de 3 elementos que multiplica a matriz D pelo vetor C :\n", np.dot(D, C))

Vetor de 3 elementos que multiplica a matriz D pelo vetor C :
 [30 36 42]


In [11]:
# Calcular o dot product de dois vetores e explicar em palavras o que significa.
A = np.array([1, 2, 1])

B = np.array([2, 2, 2])

print("Produto de 2 vetores :\n", np.dot(A, B))

print("A função interna np.dot, multiplica cada posição pela posição equivalente e ao final soma tudo")

Produto de 2 vetores :
 8
A função interna np.dot, multiplica cada posição pela posição equivalente e ao final soma tudo


---
# Matriz transposta

- Inverte linhas e colunas. Muito útil em multiplicações e operações de álgebra linear.

In [12]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Matriz original:\n\n",A,"\n\n")
print("Transposta:\n\n", A.T)

Matriz original:

 [[1 2 3 4]
 [5 6 7 8]] 


Transposta:

 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


---
# Reshape (Redimensionamento de Arrays)

- Muda a forma de um array sem alterar os dados. Ideal para preparar dados para modelos ou visualizações.

In [13]:
v = np.arange(1, 7)
print("Reshape para 2x3:\n\n", v.reshape(2, 3),"\n")
print("Reshape para 3x2:\n\n", v.reshape(3, 2))

Reshape para 2x3:

 [[1 2 3]
 [4 5 6]] 

Reshape para 3x2:

 [[1 2]
 [3 4]
 [5 6]]


---
# Multiplicação Elemento a Elemento através da matriz

In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

print("Matriz A:\n\n", A,"\n")
print("Matriz B:\n\n", B,"\n")

print("Multiplicação elemento a elemento:\n\n", A * B)

Matriz A:

 [[1 2]
 [3 4]] 

Matriz B:

 [[2 0]
 [1 3]] 

Multiplicação elemento a elemento:

 [[ 2  0]
 [ 3 12]]


---
# Inversão de Matrizes
- Usada para resolver sistemas lineares. Só funciona com matrizes quadradas e invertíveis.

In [15]:
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)

print("Matriz original:\n\n", A,"\n\n")
print("Inversa:\n\n", A_inv)

Matriz original:

 [[1 2]
 [3 4]] 


Inversa:

 [[-2.   1. ]
 [ 1.5 -0.5]]


---
# Determinante de Matrizes
- Indica se uma matriz é invertível e tem aplicações em geometria e transformações lineares.

In [16]:
A = np.array([[1, 2], [3, 4]])

print("Matriz A:\n\n", A,"\n")


print("Determinante:", np.linalg.det(A))

Matriz A:

 [[1 2]
 [3 4]] 

Determinante: -2.0000000000000004


---
# 📊 Parte 3: Estatística com NumPy
- Análise de dados, normalização, e pré-processamento em ciência de dados.

In [17]:
v = np.array([1, 2, 3, 4, 5])
print("Média Aritmética:", np.mean(v))
print("Mediana:", np.median(v))
print("\nDesvio padrão:", np.std(v))
print("Variança:", np.var(v))
print("\nMinimo:", np.min(v))
print("Máximo:", np.max(v))
print("\nSoma total dos elementos:", np.sum(v))
print("Soma acumulada:", np.cumsum(v))
print("\nProduto de todos os elementos:", np.prod(v))
print("Coeficiente de correlação entre arrays:", np.corrcoef(v))
print("\nHistograma dos dados(frequencia por intervalo):\n", np.histogram(v))
print("\nContagem de inteiros não negativos:", np.bincount(v))
print("\nValores únicos e suas contagens:", np.unique(v))
print("Indice do maior valor:", np.argmax(v))
print("Indice do menor valor:", np.argmin(v))

Média Aritmética: 3.0
Mediana: 3.0

Desvio padrão: 1.4142135623730951
Variança: 2.0

Minimo: 1
Máximo: 5

Soma total dos elementos: 15
Soma acumulada: [ 1  3  6 10 15]

Produto de todos os elementos: 120
Coeficiente de correlação entre arrays: 1.0

Histograma dos dados(frequencia por intervalo):
 (array([1, 0, 1, 0, 0, 1, 0, 1, 0, 1], dtype=int64), array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ]))

Contagem de inteiros não negativos: [0 1 1 1 1 1]

Valores únicos e suas contagens: [1 2 3 4 5]
Indice do maior valor: 4
Indice do menor valor: 0


---
# Produto Vetorial
- Retorna um vetor perpendicular aos dois vetores originais. Fundamental em física e gráficos 3D.

In [18]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
print("Produto vetorial:", np.cross(a, b))

Produto vetorial: [0 0 1]


---
# Soma e Média por Eixo 
- Permite analisar dados por dimensão (linhas ou colunas).

In [19]:
A = np.array([[1, 2], [3, 4]])
print("Soma por linha:", np.sum(A, axis=1))
print("Soma por colunA:", np.sum(A, axis=0))

print("\nMédia por linha:", np.mean(A, axis=1))
print("Média por coluna:", np.mean(A, axis=0))

Soma por linha: [3 7]
Soma por colunA: [4 6]

Média por linha: [1.5 3.5]
Média por coluna: [2. 3.]


In [20]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

print("Matriz A:\n\n", A,"\n")
print("Matriz B:\n\n", B,"\n")

print("Linha 1 de A: [1, 2]\n")
print("Coluna 1 de B: [2, 1] → 1 × 2 + 2 × 1 = 4 ")
print("Coluna 2 de B: [0, 3] → 1 × 0 + 2 × 3 = 6")

print("\n\nLinha 2 de A: [3, 4]\n\n")

print("Coluna 1 de B: [2, 1] → 3 × 2 + 4 × 1 = 10")

print("Coluna 2 de B: [0, 3] → 3 × 0 + 4 × 3 = 12\n\n")

print("Produto matricial:\n",np.dot(A,B))

Matriz A:

 [[1 2]
 [3 4]] 

Matriz B:

 [[2 0]
 [1 3]] 

Linha 1 de A: [1, 2]

Coluna 1 de B: [2, 1] → 1 × 2 + 2 × 1 = 4 
Coluna 2 de B: [0, 3] → 1 × 0 + 2 × 3 = 6


Linha 2 de A: [3, 4]


Coluna 1 de B: [2, 1] → 3 × 2 + 4 × 1 = 10
Coluna 2 de B: [0, 3] → 3 × 0 + 4 × 3 = 12


Produto matricial:
 [[ 4  6]
 [10 12]]


---
# Sistemas Lineares
- Resolve equações do tipo Ax = b. Muito usado em engenharia e modelagem matemática.

In [21]:
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])
x = np.linalg.solve(A, b)

print("Matriz A:\n\n", A,"\n")
print("Matriz B:\n\n", b,"\n")

print("Solução do sistema:", x)

Matriz A:

 [[2 1]
 [1 3]] 

Matriz B:

 [ 8 13] 

Solução do sistema: [2.2 3.6]


---
# 🧩 Aplicações Reais — Onde isso é usado?
## 🧠 1. Machine Learning
- Produto escalar é usado em redes neurais para calcular ativações.
- Magnitude é usada para normalizar vetores (ex: vetores de características).

## 📸 2. Processamento de Imagens
- Matrizes representam imagens (pixels).

- Multiplicações de matrizes são usadas em filtros, convoluções e transformações geométricas.

## 🧭 3. Física e Engenharia
- Produto escalar mede o trabalho realizado por uma força.

- Produto vetorial calcula torque ou vetores perpendiculares.

## 📈 4. Análise de Dados
- Estatísticas como média, desvio padrão e correlação são usadas para entender padrões em dados financeiros, científicos ou sociais.

## 🧮 5. Geometria Computacional
- Vetores são usados para calcular distâncias, ângulos, direções e projeções.